#!/usr/bin/env python3
"""Generate audio files for all POIs using edge-tts."""
import os, asyncio, edge_tts

AUDIO_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "server", "audio")
VOICE_DE = "de-DE-KatjaNeural"
VOICE_EN = "en-US-JennyNeural"

POIS = [
    # München
    ("muenchen-marienplatz", "Der Marienplatz ist seit 1158 das Zentrum Münchens. Das Neue Rathaus mit seinem berühmten Glockenspiel zieht täglich tausende Besucher an. Um 11 und 12 Uhr tanzen die Figuren des Glockenspiels das Schäfflertanz-Spektakel nach.", "Marienplatz has been Munich's center since 1158. The New Town Hall with its famous Glockenspiel attracts thousands daily. At 11 and 12, the Glockenspiel figures perform the Schäffler dance spectacle."),
    ("muenchen-frauenkirche", "Die Frauenkirche mit ihren markanten Zwiebeltürmen ist das Wahrzeichen Münchens. Die Dom zu Unserer Lieben Frau wurde 1494 fertiggestellt – ihre Türme sind 99 Meter hoch. Der Teufelstritt im Eingangsbereich ist eine berühmte Legende.", "The Frauenkirche with its distinctive onion domes is Munich's landmark. Completed in 1494, its towers reach 99 meters. The Devil's Footstep at the entrance is a famous local legend."),
    ("muenchen-viktualienmarkt", "Der Viktualienmarkt ist Münchens berühmtester Lebensmittelmarkt. Seit 1807 werden hier täglich frische Produkte, Blumen und bayerische Spezialitäten angeboten. Der Maibaum mit seinen bunten Wappen ist ein echter Hingucker.", "Viktualienmarkt is Munich's most famous food market. Since 1807, fresh produce, flowers and Bavarian specialties are sold here daily. The maypole with its colorful crests is a real eye-catcher."),
    ("muenchen-hofbrauhaus", "Das Hofbräuhaus ist das weltberühmteste Bierlokal Münchens. Gegründet 1589 als herzogliche Brauerei, ist es heute ein Muss für jeden Besucher. Hier wurde 1920 die erste Parteiversammlung der NSDAP abgehalten – ein düsterer Teil der Geschichte.", "The Hofbräuhaus is the world's most famous beer hall in Munich. Founded in 1589 as a ducal brewery, it's a must-visit today. In 1920, the NSDAP held its first party meeting here – a dark chapter of history."),
    ("muenchen-residenz", "Die Residenz war von 1508 bis 1918 Sitz der bayerischen Herzöge, Kurfürsten und Könige. Der Komplex ist einer der größten Innenstadt-Paläste Europas – mit über 130 Prunkräumen, die von der Macht der Wittelsbacher zeugen.", "The Residence was the seat of Bavarian dukes, prince-electors and kings from 1508 to 1918. It's one of Europe's largest city palaces – with over 130 state rooms testifying to the power of the Wittelsbach dynasty."),
    ("muenchen-odeonsplatz", "Der Odeonsplatz ist einer der schönsten Plätze Münchens, umrahmt von der Feldherrnhalle, der Theatinerkirche und der Residenz. Hier spielte sich 1923 der gescheiterte Hitler-Putsch ab, der später von den Nazis glorifiziert wurde.", "Odeonsplatz is one of Munich's most beautiful squares, framed by the Feldherrnhalle, Theatiner Church and the Residence. The failed Hitler Putsch of 1923 took place here, later glorified by the Nazis."),
    ("muenchen-englischer-garten", "Der Englische Garten ist eine der größten innerstädtischen Parkanlagen der Welt – größer als der Central Park in New York. Der Chinesische Turm, der Biergarten und die Eisbach-Welle mit ihren Surfern sind echte Münchner Institutionen.", "The English Garden is one of the world's largest inner-city parks – larger than New York's Central Park. The Chinese Tower, the beer garden and the Eisbach Wave with its surfers are true Munich institutions."),
    ("muenchen-siegestor", "Das Siegestor wurde 1852 von König Ludwig I. erbaut und dem bayerischen Heer gewidmet. Nach dem Zweiten Weltkrieg wurde es wieder aufgebaut – mit der Inschrift 'Dem Sieg geweiht, vom Krieg zerstört, zum Frieden mahnend'.", "The Victory Gate was built in 1852 by King Ludwig I and dedicated to the Bavarian army. Rebuilt after WWII with the inscription 'Dedicated to victory, destroyed by war, reminding us of peace'."),
    ("muenchen-pinakotheken", "Die Pinakotheken gehören zu den bedeutendsten Kunstmuseen der Welt. Die Alte Pinakothek zeigt Meisterwerke von Dürer bis Rubens, die Neue Pinakothek Kunst des 18. und 19. Jahrhunderts. Ein Paradies für Kunstliebhaber.", "The Pinakotheken rank among the world's most important art museums. The Old Pinakothek shows masterpieces from Dürer to Rubens, the New Pinakothek 18th and 19th century art. A paradise for art lovers."),
    # Hamburg
    ("hamburg-rathaus", "Das Hamburger Rathaus ist ein prächtiger Neorenaissance-Bau von 1897. Mit 647 Räumen ist es größer als der Buckingham Palace. Der Rathausmarkt mit dem Bismarck-Denkmal ist das politische Zentrum der Hansestadt.", "Hamburg City Hall is a magnificent Neo-Renaissance building from 1897. With 647 rooms, it's larger than Buckingham Palace. The Rathausmarkt with the Bismarck monument is the political center of the Hanseatic city."),
    ("hamburg-kleine-alster", "Die Kleine Alster ist das Herz der Hamburger Innenstadt. Hier treffen sich Jung und Alt an den Alsterarkaden – den romantischen Bogengängen im italienischen Stil. Die Alster-Schwäne sind ein Symbol der Stadt.", "The Kleine Alster is the heart of downtown Hamburg. People gather at the Alster Arcades – romantic arched walkways in Italian style. The Alster swans are a symbol of the city."),
    ("hamburg-speicherstadt", "Die Speicherstadt ist das größte zusammenhängende Lagerhaus-Ensemble der Welt. Seit 2015 UNESCO-Weltkulturerbe, erstreckt sie sich über 26 Hektar mit roten Backsteinbauten auf Eichenpfählen – das Herz des Hamburger Hafens seit 1888.", "The Speicherstadt is the world's largest coherent warehouse complex. A UNESCO World Heritage site since 2015, it spans 26 hectares with red brick buildings on oak piles – the heart of Hamburg's port since 1888."),
    ("hamburg-elbphilharmonie", "Die Elbphilharmonie ist das neue Wahrzeichen Hamburgs. Der 110 Meter hohe Glaskristall auf dem alten Kaispeicher A beherbergt einen der besten Konzertsäle der Welt. Der Plaza-Besuch in 37 Metern Höhe ist kostenlos.", "The Elbphilharmonie is Hamburg's new landmark. The 110-meter glass crystal atop the old Kaispeicher A houses one of the world's best concert halls. The Plaza visit at 37 meters is free."),
    ("hamburg-landungsbruecken", "Die Landungsbrücken sind das maritime Herz Hamburgs. Seit 1910 legen hier die Hafenrundfahrtschiffe und Fähren ab. Von hier haben Sie den besten Blick auf den Hafen, die Elbphilharmonie und die vorbeiziehenden Containerschiffe.", "The Landungsbrücken are Hamburg's maritime heart. Since 1910, harbor tour boats and ferries depart from here. You get the best view of the harbor, the Elbphilharmonie, and passing container ships."),
    ("hamburg-alter-elbtunnel", "Der Alte Elbtunnel von 1911 ist ein technisches Meisterwerk. 426 Meter lang verbindet er auf 24 Metern Tiefe die Landungsbrücken mit der anderen Elbseite. Die originalen Aufzüge befördern Autos und Fußgänger.", "The Old Elbe Tunnel from 1911 is an engineering masterpiece. 426 meters long at 24 meters depth, it connects the Landungsbrücken to the other side of the Elbe. The original elevators carry cars and pedestrians."),
    ("hamburg-fischmarkt", "Der Fischmarkt ist seit 1703 ein Hamburger Kulturgut. Jeden Sonntagmorgen ab 5 Uhr wird hier lauthals gefeilscht – 'Fischkopp'-Kultur pur. In der benachbarten Großen Freiheit liegen berühmte Musikclubs wie der Kaiserkeller, wo die Beatles spielten.", "The Fish Market has been a Hamburg cultural institution since 1703. Every Sunday from 5 AM, loud haggling takes place – pure 'Fischkopp' culture. Nearby Große Freiheit hosts famous music clubs like the Kaiserkeller where the Beatles played."),
    ("hamburg-planten-blomen", "Planten un Blomen – Plattdeutsch für 'Pflanzen und Blumen' – ist ein 47 Hektar großer Park im Herzen Hamburgs. Der japanische Teegarten, die großen Gewächshäuser und die Wasserspiele mit Lichtershows im Sommer sind einzigartig.", "Planten un Blomen – Low German for 'Plants and Flowers' – is a 47-hectare park in the heart of Hamburg. The Japanese tea garden, large greenhouses and water-light shows in summer are unique."),
    ("hamburg-hafencity", "Die HafenCity ist Europas größtes innerstädtisches Stadtentwicklungsprojekt. Auf 157 Hektar entsteht ein komplett neuer Stadtteil mit modernster Architektur. Das Überseequartier und die Marco-Polo-Terrassen sind das neue Gesicht Hamburgs.", "HafenCity is Europe's largest inner-city urban development project. A completely new district with cutting-edge architecture is being built on 157 hectares. The Überseequartier and Marco Polo Terraces are Hamburg's new face."),
]

async def generate_all():
    os.makedirs(AUDIO_DIR, exist_ok=True)
    for i, (pid, text_de, text_en) in enumerate(POIS, 1):
        for lang, text, voice in [("de", text_de, VOICE_DE), ("en", text_en, VOICE_EN)]:
            fname = f"{pid}_{lang}.mp3"
            fp = os.path.join(AUDIO_DIR, fname)
            if os.path.exists(fp):
                print(f"[{i}/{len(POIS)}] SKIP {fname}")
                continue
            print(f"[{i}/{len(POIS)}] Generating {fname}...")
            await edge_tts.Communicate(text, voice).save(fp)
    print(f"\nDone! {len(POIS)} POIs × 2 = {len(POIS)*2} files")

asyncio.run(generate_all())
